<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Svea\\WebPay\\' => array($baseDir . '/sveaekonomi/webpay/src', $vendorDir . '/sveaekonomi/webpay/src'),
    'Svea\\Checkout\\' => array($baseDir . '/sveaekonomi/checkout/src', $vendorDir . '/sveaekonomi/checkout/src'),
);
