<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1a778baa5fcbd8a2a47f867c789902d5
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Svea\\WebPay\\' => 12,
            'Svea\\Checkout\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Svea\\WebPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/svea/webpay/src',
        ),
        'Svea\\Checkout\\' => 
        array (
            0 => __DIR__ . '/..' . '/svea/checkout-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1a778baa5fcbd8a2a47f867c789902d5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1a778baa5fcbd8a2a47f867c789902d5::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
