<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Svea\\WebPay\\' => array($vendorDir . '/sveaekonomi/webpay/src'),
    'Svea\\Checkout\\' => array($vendorDir . '/sveaekonomi/checkout/src'),
);
